# Generated by Django 5.2.4 on 2026-02-21 16:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coingecko_id", models.CharField(max_length=100, unique=True)),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("market_cap_rank", models.IntegerField(blank=True, null=True)),
                ("total_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "price_change_1h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "price_change_7d",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ath",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("ath_date", models.DateTimeField(blank=True, null=True)),
                (
                    "atl",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("atl_date", models.DateTimeField(blank=True, null=True)),
                (
                    "circulating_supply",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=30, null=True
                    ),
                ),
                (
                    "total_supply",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=30, null=True
                    ),
                ),
                (
                    "max_supply",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=30, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["market_cap_rank"],
            },
        ),
        migrations.CreateModel(
            name="AlertSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("browser_notifications", models.BooleanField(default=False)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                        ],
                        default="instant",
                        max_length=10,
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("above", "Price Above"),
                            ("below", "Price Below"),
                            ("change_up", "% Change Up"),
                            ("change_down", "% Change Down"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("once", "Once"), ("always", "Always")],
                        default="once",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="coins.coin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Portfolio", max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("receive", "Receive"),
                            ("send", "Send"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    "price_per_coin",
                    models.DecimalField(
                        decimal_places=10, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=10, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("exchange", models.CharField(blank=True, default="", max_length=100)),
                ("wallet", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                ("transacted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="coins.coin",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="coins.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-transacted_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("JPY", "Japanese Yen (¥)"),
                            ("KES", "Kenyan Shilling (KSh)"),
                            ("NGN", "Nigerian Naira (₦)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("Africa/Nairobi", "Africa/Nairobi (EAT)"),
                            ("Africa/Lagos", "Africa/Lagos (WAT)"),
                            ("America/New_York", "America/New_York (EST)"),
                            ("America/Los_Angeles", "America/Los_Angeles (PST)"),
                            ("Europe/London", "Europe/London (GMT)"),
                            ("Asia/Tokyo", "Asia/Tokyo (JST)"),
                        ],
                        default="UTC",
                        max_length=50,
                    ),
                ),
                (
                    "number_format",
                    models.CharField(
                        choices=[
                            ("1,234.56", "1,234.56"),
                            ("1.234,56", "1.234,56"),
                            ("1 234.56", "1 234.56"),
                        ],
                        default="1,234.56",
                        max_length=10,
                    ),
                ),
                ("show_portfolio_chart", models.BooleanField(default=True)),
                ("show_allocation", models.BooleanField(default=True)),
                ("show_recent_activity", models.BooleanField(default=True)),
                ("show_top_holdings", models.BooleanField(default=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("is_pro", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=10, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "avg_buy_price",
                    models.DecimalField(
                        decimal_places=10, default=Decimal("0"), max_digits=30
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="coins.coin",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="coins.portfolio",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "coin")},
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlisted_by",
                        to="coins.coin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "coin")},
            },
        ),
    ]
